# Generated by Django 4.2.1 on 2023-05-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('unsend_message', 'Can unsend message')]},
        ),
    ]
