# Generated by Django 4.2 on 2023-04-29 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_usersettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcontent',
            name='reason',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterUniqueTogether(
            name='reportedcontent',
            unique_together={('reported_by', 'message')},
        ),
    ]
